spring.application.name=backend

# ??? ???(SQL)? ???? ??
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 DB ? ?? ?? ??
spring.h2.console.enabled=true
spring.h2.consloe.path=/h2-console

# H2 DB URL? 'testdb'? ?! ????
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ????? ???? ?? ??
spring.web.resources.static-locations=file:../FrontEnd/,file:./FrontEnd/,classpath:/static/

spring.profiles.include=secret