weather:
  api:
    key: "4b38224fb78fc85053c45014bb4f4c261df29599efd273c8c5daf763aeca4a95"
    url: "https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"

kakao:
  api:
    key: "985977e649543f1eae7669fde7cee88c"
    url: "https://dapi.kakao.com/v2/local/search/address.json"